<?php
$message ='
http://gsaserver.technideus.com/public/activation?key='.$code.'&domid='.$domin_id;
$oldmessage = '<center style="min-width:580px;width:100%">
 <table style="border-collapse:collapse;border-spacing:0;margin:0 auto;padding:0;text-align:inherit;vertical-align:top;width:580px">
 <tbody>
    <tr style="padding:0;text-align:left;vertical-align:top" align="left">
        <td style="border-collapse:collapse!important;color:#222222;font-family:"Helvetica","Arial",sans-serif;font-size:14px;font-weight:normal;line-height:19px;margin:0;padding:0;text-align:left;vertical-align:top;word-break:break-word" align="left" valign="top">
        <table style="border-collapse:collapse;border-spacing:0;margin-top:20px;padding:0;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top" align="left"><td align="center" style="border-collapse:collapse!important;color:#222222;font-family:"Helvetica","Arial",sans-serif;font-size:14px;font-weight:normal;line-height:19px;margin:0;padding:0;text-align:center;vertical-align:top;word-break:break-word" valign="top"><center style="min-width:580px;width:100%"><div style="margin-bottom:30px;margin-top:20px;text-align:center!important" align="center !important">
        
        <img src="http://gsa.technideus.com/assets/logos/app-logo.png" style="clear: both;display: block;float: none;height: 50px;margin: 0 auto; outline: none;text-decoration: none;width: 200px;" align="none">
        </div>
        </center>
        </td>
        <td style="border-collapse:collapse!important;color:#222222;font-family:"Helvetica","Arial",sans-serif;font-size:14px;font-weight:normal;line-height:19px;margin:0;padding:0;text-align:left;vertical-align:top;width:0px;word-break:break-word" align="left" valign="top"></td></tr></tbody>
        </table>
        <table style="background:#ffffff;border-collapse:collapse;border-radius:3px!important;border-spacing:0;border:1px solid #dddddd;padding:0;text-align:left;vertical-align:top" bgcolor="#ffffff">
        <tbody>
        <tr style="padding:0;text-align:left;vertical-align:top" align="left">
        <td style="border-collapse:collapse!important;color:#222222;font-family:"Helvetica","Arial",sans-serif;font-size:14px;font-weight:normal;line-height:19px;margin:0;padding:0;text-align:left;vertical-align:top;word-break:break-word" align="left" valign="top">
        <div style="color:#333333;font-size:14px;font-weight:normal;line-height:20px;margin:20px"><table style="background:#fff;border-collapse:separate!important;border-spacing:0;box-sizing:border-box;color:#222222;font-family:"Helvetica","Arial",sans-serif;font-size:14px;font-weight:normal;height:100%;line-height:19px;margin:0;padding:10px;text-align:left;vertical-align:top;width:100%" width="100%" bgcolor="#fff">
        <tbody>
        <tr style="padding:0;text-align:left;vertical-align:top" align="left">
        <td style="border-collapse:collapse!important;box-sizing:border-box;color:#222222;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";font-size:14px;font-weight:normal;line-height:19px;margin:0;padding:0;text-align:left;vertical-align:top;word-break:break-word" valign="top" align="left">
        </td>
        <td style="border-collapse:collapse!important;box-sizing:border-box;color:#222222;display:block;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";font-size:14px;font-weight:normal;line-height:19px;margin:0 auto;max-width:580px;padding:24px;text-align:left;vertical-align:top;width:580px;word-break:break-word" width="580" valign="top" align="left"><div style="box-sizing:border-box;display:block;margin:0 auto;max-width:580px"> <span style="color:transparent;display:none;height:0;max-height:0;max-width:0;opacity:0;overflow:hidden;width:0">To secure your GSA account, we just need to verify your email address: <a class="m_-2619863381494479990plaintext" href="mailto:'.$email_id.'" style="color:#2ba6cb;text-decoration:none" target="_blank">'.$email_id.'</a>.</span>
        <h1 style="color: #586069;font-family: -apple-system,BlinkMacSystemFont,;font-size: 20px;/* font-style: inherit; */font-weight: 400;margin-bottom: 20px;" > Almost done, <strong style="color:#24292e!important">@'.$name.'</strong>! To complete your GSA sign up, we just need to verify your email address: <strong style="color:#24292e!important"><a href="mailto:'.$email_id.'" target="_blank">'.$email_id.'</a></strong>.</h1><table cellpadding="0" cellspacing="0" style="border-collapse:separate!important;border-spacing:0;box-sizing:border-box;margin:0 0 30px;padding:0;text-align:left;vertical-align:top;width:100%" width="100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top" align="left"><td align="" style="border-collapse:collapse!important;box-sizing:border-box;color:#222222;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";font-size:14px;font-weight:normal;line-height:19px;margin:0;padding:0;text-align:left;vertical-align:top;word-break:break-word" valign="top"><table cellpadding="0" cellspacing="0" style="border-collapse:separate!important;border-spacing:0;box-sizing:border-box;padding:0;text-align:left;vertical-align:top;width:auto"><tbody><tr style="padding:0;text-align:left;vertical-align:top" align="left"><td style="background:#0366d6;border-collapse:collapse!important;border-radius:5px;box-sizing:border-box;color:#222222;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";font-size:14px;font-weight:normal;line-height:19px;margin:0;padding:0;text-align:center;vertical-align:top;word-break:break-word" valign="top" bgcolor="#0366d6" align="center"> <a style="background:#0366d6;border-radius:5px;border:1px solid #0366d6;box-sizing:border-box;color:#ffffff;display:inline-block;font-size:14px;font-weight:bold;margin:0;padding:10px 20px;text-decoration:none" href="http://gsaserver.technideus.com/public/activation?key='.$code.'&domid='.$domin_id.'" target="_blank" >Verify email address</a></td></tr></tbody></table></td></tr></tbody></table>
            <p style="color:#222222;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";font-size:14px;font-weight:normal;line-height:1.5;margin:0 0 15px;padding:0;text-align:left" align="left">Once verified, you can start using all of GSA features to explore, build, and share projects.</p><p style="color:#586069!important;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";font-size:12px!important;font-weight:normal;line-height:1.5;margin:0 0 15px;padding:0;text-align:left" align="left">Button not working? Paste the following link into your browser:</p> 
        
            <a style="box-sizing:border-box;color:#0366d6;text-decoration:none;word-break:break-all" href="http://gsaserver.technideus.com/public/activation?key='.$code.'&domid='.$domin_id.'" target="_blank > http://gsaserver.technideus.com/public/activation?key='.$code.'&domid='.$domin_id.'</a>
        
        <p style="color:#586069!important;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";font-size:12px!important;font-weight:normal;line-height:1.5;margin:0 0 15px;padding:0;text-align:left" align="left">
        
        You’re receiving this email because you recently created a new GSA account or added a new email address. If this wasn’t you, please ignore this email.</p>
        
        <div style="box-sizing:border-box;clear:both;width:100%"><hr style="background:#d9d9d9;border-style:solid none none;border-top-color:#e1e4e8;border-width:1px 0 0;color:#959da5;font-size:12px;height:0;line-height:18px;margin:24px 0 30px;overflow:visible"><div style="box-sizing:border-box;color:#959da5;font-size:12px;line-height:18px"><p style="color:#959da5;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";font-size:12px;font-weight:normal;line-height:18px;margin:0 0 15px;padding:0;text-align:center" align="center">	<a href="#" style="box-sizing:border-box;color:#959da5;font-size:12px;line-height:18px;text-decoration:none" target="_blank" data-saferedirecturl="#">Email preferences</a> ·	<a style="box-sizing:border-box;color:#959da5;font-size:12px;line-height:18px;text-decoration:none">Terms</a> ·	<a style="box-sizing:border-box;color:#959da5;font-size:12px;line-height:18px;text-decoration:none">Privacy</a> ·	<a href="#" style="box-sizing:border-box;color:#959da5;font-size:12px;line-height:18px;text-decoration:none" target="_blank" data-saferedirecturl="#">Sign into GSA</a></p></div></div></div></td><td style="border-collapse:collapse!important;box-sizing:border-box;color:#222222;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";font-size:14px;font-weight:normal;line-height:19px;margin:0;padding:0;text-align:left;vertical-align:top;word-break:break-word" valign="top" align="left"></td></tr></tbody></table></div></td></tr></tbody></table><table style="border-collapse:collapse;border-spacing:0;margin-bottom:30px;padding:0;text-align:left;vertical-align:top;width:100%"><tbody><tr style="padding:0;text-align:left;vertical-align:top" align="left"><td align="center" style="border-collapse:collapse!important;color:#222222;font-family:"Helvetica","Arial",sans-serif;font-size:14px;font-weight:normal;line-height:19px;margin:0;padding:0;text-align:center;vertical-align:top;word-break:break-word" valign="top"><center style="min-width:580px;width:100%"><div style="margin-bottom:25px;margin-top:25px;text-align:center!important" align="center !important"> 
            <img src="http://gsa.technideus.com/assets/logos/app-logo.png" style="clear: both;display: block;float: none;height: 50px;margin: 0 auto;outline: none;text-decoration: none;width: 150px;" align="none">
            </div>
        <p style="color:#888888;font-family:"Helvetica","Arial",sans-serif;font-size:12px;font-weight:normal;line-height:1.5;margin:0 0 10px;padding:0;text-align:center" align="center">Sent with &lt;3 by <strong>GSA</strong>. <br>GSA, Inc. 88 Colin P Kelly Jr Street <br>San Francisco, CA 94107</p></center></td><td style="border-collapse:collapse!important;color:#222222;font-family:"Helvetica","Arial",sans-serif;font-size:14px;font-weight:normal;line-height:19px;margin:0;padding:0;text-align:left;vertical-align:top;width:0px;word-break:break-word" align="left" valign="top"></td></tr></tbody></table></td></tr></tbody></table></center>';
